# This workflow is based on the old travis-ci configuration and built from a github actions workflow template.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: docs

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  docs_build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
        mpi: ['mpich']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Pre-installation
      run: |
        python --version
        uname -a
    - name: Install MPI (${{ matrix.mpi }})
      run: |
        python --version
        uname -a
        lsb_release -a || true
        bash ci/mpi/install-mpi.sh ${{ matrix.mpi }}
        if [[ ${{ matrix.mpi }} == "mpich"   ]]; then mpichversion; fi
    - name: Install installer dependencies
      run: |
        python -mpip install --progress-bar=off tox pip virtualenv
        virtualenv --version
        pip --version
        tox --version
    - name: Build docs
      run: |
        tox -v -e docs
