# This workflow is based on the old travis-ci configuration and built from a github actions workflow template.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: check

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  check_standards:
    name: code style
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Pre-installation
      run: |
        python --version
        uname -a
    - name: Install installer dependencies
      run: |
        python -mpip install --progress-bar=off tox -rci/requirements.txt
        virtualenv --version
        pip --version
        tox --version
    - name: Run coding style check
      run: |
        tox -v -e check
